### ISSUE TITLE
`$` character in text body throws exception

### ISSUE THREAD

**Issue by v411e** [silverbulletmd/silverbullet-ghost#3]
# Steps to reproduce
When sharing a ghost post that has a `$` character in the text body, the following exception is thrown:
```log
Post should stat with a # header
Stack trace: Error: Post should stat with a # header
    at we (eval at <anonymous> (blob:null/7ef28546-dfb0-49f2-84e1-3dab5dd37df2:1:1706), <anonymous>:3:8760)
    at B (eval at <anonymous> (blob:null/7ef28546-dfb0-49f2-84e1-3dab5dd37df2:1:1706), <anonymous>:3:9127)
    at async blob:null/7ef28546-dfb0-49f2-84e1-3dab5dd37df2:1:2013
Stack trace: Error: Post should stat with a # header
Stack trace: Error: Post should stat with a # header
    at we (eval at <anonymous> (blob:null/7ef28546-dfb0-49f2-84e1-3dab5dd37df2:1:1706), <anonymous>:3:8760)
    at B (eval at <anonymous> (blob:null/7ef28546-dfb0-49f2-84e1-3dab5dd37df2:1:1706), <anonymous>:3:9127)
    at async blob:null/7ef28546-dfb0-49f2-84e1-3dab5dd37df2:1:2013
    at blob:null/ec2700b3-4337-40f4-a9ef-9cff284a6f37:1:2338
    at l (blob:null/ec2700b3-4337-40f4-a9ef-9cff284a6f37:1:38)
    at blob:null/ec2700b3-4337-40f4-a9ef-9cff284a6f37:1:1648
    at innerInvokeEventListeners (deno:ext/web/02_event.js:755:9)
    at invokeEventListeners (deno:ext/web/02_event.js:795:7)
    at dispatch (deno:ext/web/02_event.js:664:11)
    at dispatchEvent (deno:ext/web/02_event.js:1043:14)
    at pollForMessages (deno:runtime/js/99_main.js:159:9)
```

# Outcome
## What did you expect?
I expected the post to be shared with ghost.

## What happened instead?
The error was thrown and the post was not shared with ghost.

**Comment by zefhemel** [comment]
I cannot replicate this, can you share a minimal example of where this happens? Do note that you need to have a `# Header` at the top of your page (the plug extracts this and uses it as a title). For example:

<img width="839" alt="CleanShot 2023-05-17 at 17 42 59@2x" src="https://github.com/silverbulletmd/silverbullet-ghost/assets/59073/6b7784ed-d0dd-4c0e-85ca-6365f22b69cd">

**Comment by zefhemel** [comment]
Hang on, found it.

**Comment by zefhemel** [comment]
Reloading plugs should fix it

**Comment by v411e** [comment]
Many thanks!
